### PR TITLE
Add a tool to help build self-contained postgresql package

### PR DESCRIPTION
**Pull request by mflu**
A tool to help build a postgresql package which could be re-located anywhere (only validated in stemcell 0.8.0 based on ubuntu 10.04)

### CODE REVIEW

**Comment by mflu** [comment]
@kushmerick @andl @figof 
Could you help review this?

**Comment by drnic** [comment]
This is a cool idea to bring some of the preparation scripts out of cf-release for non-bosh users.

**Comment by andreacampi** [comment]
Seconded.

**Comment by andl** [comment]
@EagleChen can we refine and submit the mysql package script to vcap-services as well?

**Comment by EagleChen** [comment]
@andl  yes, of course. I will create a pivotal story for this.

**Comment by kushmerick** [comment]
+2 -- looks good to commit.  but why does CI fail?  I think there is no problem with this commit, CI is broken, so it is OK to merge?

**Comment by mflu** [comment]
@kushmerick 

From the CI build history, https://travis-ci.org/cloudfoundry/vcap-services/builds
I don't think the failure of CI is caused my pull request For there is not any successful CI run since build 27.

The errors are: 
$ rake
rake aborted!
Don't know how to build task 'default'
(See full trace by running task with --trace)
The command "rake" exited with 1.
Done. Your build exited with 1.

Do we make the CI work well?

**Comment by figof** [comment]
I talked to Shannon and David, they will fix the CI tomorrow. But I think it's good to merge the codes now.

**Pull request merged**
