### PR TITLE
Addition of the Neo4j Graph Database as a service to run within CloudFoundry

### PR DESCRIPTION
**Pull request by jexp**
We provided support for installing (vcap_setup) Neo4j server and hosting extension into /var/vcap/service/neo4j

We added the necessary scripts for starting the nodes and provisioning gateway.

Also provided the scripts that allow provisioning/unprovisioning by creating a separate server instance per service provisioning request, creating admin credentials.

For binding requests another set of credentials is created and a read-write or read-only user is added to the running server using its admin API (contained in neo4j-hosting-extension)

### CODE REVIEW

**Comment by pbozeman** [comment]
This is great!  Can you add a simple cucumber feature to vcap-tests cucumber to do a few basic ops against neo4j such that the app returns success/failure back to the the test?  The steps portion of the test should just go 'pending' if the service isn't available.

Thanks

**Comment by jexp** [comment]
Suddenly all my service provisionings from vmc fail with (I'll attach a mongo example so that it's clear it is nothing affected by my neo4j changes) - would love to get some additional diagnosis tips.

# vcap tail output

```
mongodb_gateway --> D, [2011-05-19T12:00:52.218741 #6679] DEBUG -- : Provision request for label=mongodb-1.8 plan=free
mongodb_gateway --> D, [2011-05-19T12:00:52.218901 #6679] DEBUG -- : [MongoaaS-Provisioner] Attempting to provision instance (version=1.8, plan=free)
   mongodb_node --> D, [2011-05-19T12:00:52.259181 #6698] DEBUG -- : MongoaaS-Node: Sending announcement for _INBOX.dd0b728944aee769bdbfef682c
mongodb_gateway --> D, [2011-05-19T12:00:52.263536 #6679] DEBUG -- : [MongoaaS-Provisioner] Found the following nodes: [["{\"available_memory\":4096,\"id\":\"mongodb_node_1\"}", nil]]
mongodb_gateway -->
mongodb_gateway --> D, [2011-05-19T12:00:52.263650 #6679] DEBUG -- : [MongoaaS-Provisioner] Provisioning node (version=1.8, plan=free, nnodes=1)
mongodb_gateway --> D, [2011-05-19T12:00:52.263750 #6679] DEBUG -- : [MongoaaS-Provisioner] Provisioning on mongodb_node_1
   mongodb_node --> D, [2011-05-19T12:00:52.264127 #6698] DEBUG -- : MongoaaS-Node: Provision request: {"plan":"free"} from _INBOX.ce774ded8ac6864615091eb153
   mongodb_node --> D, [2011-05-19T12:00:52.503829 #6698] DEBUG -- : Starting: #<VCAP::Services::MongoDB::Node::ProvisionedService @name="mongodb-eef7587b-0dbf-45dd-b84d-1ea4298850ac" @port=25001 @password="fa7bcec0-d1b1-4b71-91
66-3bd02e77b777" @plan=:free @pid=nil @memory=128 @admin=nil @adminpass=nil @db=nil>
   mongodb_node -->
   mongodb_node --> D, [2011-05-19T12:00:52.528703 #6698] DEBUG -- : Service mongodb-eef7587b-0dbf-45dd-b84d-1ea4298850ac started with pid 9141
   mongodb_node --> I, [2011-05-19T12:00:52.937667 #6698]  INFO -- : add admin user: req {:port=>25001, :username=>"admin", :password=>"9110baff-40c4-4025-8e30-6160c01e6460", :db=>"db", :times=>10}
   mongodb_node --> all output going to: /var/vcap/services/mongodb/instances/mongodb-eef7587b-0dbf-45dd-b84d-1ea4298850ac/log
   mongodb_node --> W, [2011-05-19T12:00:52.971928 #6698]  WARN -- : Failed to connect to a master node at 127.0.0.1:25001 failed 1 times
mongodb_gateway --> I, [2011-05-19T12:00:53.705964 #6679]  INFO -- : Sending info to cloud controller: http://api.vcap.me/services/v1/offerings
cloud_controller --> [2011-05-19 12:00:53 +0200, :USER, "N/A", "POST:/services/v1/offerings", :SUCCEEDED]
mongodb_gateway --> I, [2011-05-19T12:00:53.884354 #6679]  INFO -- : Successfully registered with cloud controller
   mongodb_node --> D, [2011-05-19T12:00:54.265202 #6698] DEBUG -- : user added
   mongodb_node --> I, [2011-05-19T12:00:54.265430 #6698]  INFO -- : add admin user: req {:port=>25001, :username=>"admin", :password=>"9110baff-40c4-4025-8e30-6160c01e6460", :db=>"admin", :times=>3}
   mongodb_node --> D, [2011-05-19T12:00:54.411202 #6698] DEBUG -- : user added
   mongodb_node --> D, [2011-05-19T12:00:54.411348 #6698] DEBUG -- : response: {"hostname"=>"88.198.210.199", "port"=>25001, "password"=>"fa7bcec0-d1b1-4b71-9166-3bd02e77b777", "name"=>"mongodb-eef7587b-0dbf-45dd-b84d-1ea4298850
ac", "db"=>"db"}
   mongodb_node --> D, [2011-05-19T12:00:54.411455 #6698] DEBUG -- : MongoaaS-Node: Successfully provisioned service for request {"plan":"free"}: {"hostname"=>"88.198.210.199", "port"=>25001, "password"=>"fa7bcec0-d1b1-4b71-9166
-3bd02e77b777", "name"=>"mongodb-eef7587b-0dbf-45dd-b84d-1ea4298850ac", "db"=>"db", "node_id"=>"mongodb_node_1"}
 health_manager --> Analyzed 0 running and 0 down apps in 0.0ms
            dea --> D, [2011-05-19T12:01:00.575919 #6485] DEBUG -- : DEA received router start message: {"id":"10c3c9e0acb03f71e69a7604dc453551","version":0.98}
cloud_controller --> [2011-05-19 12:01:02 +0200, :USER, "test@test.de", "POST:/services", "mongodb", "mongodb-89196", :FAILED, "Unexpected response from service gateway"]
```

# development.log: 

```
  Processing by ServicesController#create as HTML
  Parameters: {"label"=>"mongodb-1.8", "url"=>"http://127.0.0.1:57331", "plans"=>["free"], "tags"=>["mongodb", "mongodb-1.6", "nosql"], "active"=>true, "description"=>"MongoDB NoSQL store", "plan_options"=>nil, "acls"=>nil}
Create service request: {:label=>"mongodb-1.8", :url=>"http://127.0.0.1:57331", :plans=>["free"], :tags=>["mongodb", "mongodb-1.6", "nosql"], :active=>true, :description=>"MongoDB NoSQL store"}
  ESC[1mESC[36mCACHE (0.0ms)ESC[0m  ESC[1mSELECT "services".* FROM "services" WHERE "services"."label" = 'mongodb-1.8' LIMIT 1ESC[0m
  ESC[1mESC[35mService Load (0.2ms)ESC[0m  SELECT "services"."id" FROM "services" WHERE ("services"."label" = 'mongodb-1.8') AND ("services".id <> 3) LIMIT 1
  ESC[1mESC[36mAREL (0.2ms)ESC[0m  ESC[1mUPDATE "services" SET "acls" = NULL, "binding_options" = NULL, "plan_options" = NULL, "plans" = '--- 
- free
', "tags" = '--- 
- mongodb
- mongodb-1.6
- nosql
' WHERE "services"."id" = 3ESC[0m
Completed 200 OK in 73ms (Views: 0.2ms | ActiveRecord: 0.3ms)
Error talking to gateway: Error sending provision request for {"label":"mongodb-1.8","name":"mongodb-89196","plan":"free","plan_option":null}: non 200 response from gateway http://127.0.0.1:57331: 503 {}
Completed   in 10409ms
```

**Comment by pbozeman** [comment]
Can you take this issue to http://support.cloudfoundry.com/?  You can click on New over on the right side to create a ticket for this.  

That being said, the key issue in the log here is: 

mongodb_node --> W, [2011-05-19T12:00:52.971928 #6698]  WARN -- : Failed to connect to a master node at 127.0.0.1:25001 failed 1 times

That line means that the mongo_node can't talk to the mongo service that it tried to start.  If this is happening systematically to all your services, my initial guess is that somehow your directory permissions changed somewhere along the path to the persistent storage for the services.  In the mongo case above, this is /var/vcap/services/mongodb/instances/mongodb-eef7587b-0dbf-45dd-b84d-1ea4298850ac.  That directory _should_ exist and if it does, there should be a 'log' file in it specific to mongo.

Based on your logs above, you should have a mongodb process listening on port 25001 and using the directory above for the persistent storage.  I'd start with the storage.  (For example, did you run vcap start as root one time and not as root as another?  That would cause the permissions to get messed up)

If inspecting /var/vcap/service/\* doesn't shed any light on the issue, please take this over to the url at the top of this comment.

Thanks

**Comment by pbozeman** [comment]
Fyi, to anyone following this one.. it has been open for awhile, but jexp and I have been working it offline.

This one is pretty close minus some install issues.

**Comment by pbozeman** [comment]
oops.. didn't mean to close this :)

**Comment by pbozeman** [comment]
merged to master.

Thanks

**Pull request closed without merging**
