### PR TITLE
create healthz & varz handler to avoid collector's warning

### PR DESCRIPTION
**Pull request by felixhoo**

### CODE REVIEW

**Comment by kushmerick** [comment]
-1

**Comment by dsboulder** [comment]
Good catch Nick.  Felix, can you change the response of /health to be "OK" instead of "{}"?  Also please add a simple rack test that hits those 2 endpoints and asserts that they match their expected value.

**Comment by felixhoo** [comment]
Update healthz's response & spec.

**Comment by kushmerick** [comment]
+1 thanks felix.

**Pull request merged**
